apiVersion: apps/v1
kind: Deployment
metadata:
  name: lummilo-frontend
  labels:
    app: lummilo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lummilo-frontend
  template:
    metadata:
      labels:
        app: lummilo-frontend
    spec:
      containers:
      - name: lummilo-frontend-container
        image: 121775527711.dkr.ecr.us-east-1.amazonaws.com/lummilo-frontend:27-a934ebd
        ports:
        - containerPort: 80
        env:
        - name: VITE_BACKEND_API_URL
          value: "https://lummilo.syedtalhahussain.com/api"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        
