apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lummilo-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: shared-alb-group  #Same group name
spec:
  ingressClassName: alb
  rules:
    - host: lummilo.syedtalhahussain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lummilo-frontend-service
                port:
                  number: 80
    - host: api.syedtalhahussain.com  # Backend ke liye alag subdomain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lummilo-backend-service
                port:
                  number: 80
